config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: :show
  resources :articles, only: [:index, :show]
  resources :contacts, only: [:new, :create]

  get :frequently_asked_questions, to: 'frequently_asked_questions#index', path: 'frequently-asked-questions'

  %w( 403 404 422 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  mount Optimadmin::Engine => "/admin"
  root to: 'application#index'

  match "*path", to: "errors#show", via: :all, code: 404 unless Rails.application.config.consider_all_requests_local

end
Optimadmin::Engine.routes.draw do
  resources :contact_query_types, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  get 'article/index'

  get 'article/show'

  resources :articles, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  get 'frequently_asked_questions/index'

  resources :frequently_asked_questions, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :interests, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :additional_contents, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :home_page_banners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :home_page_banners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end

  resources :pages, except: :show do
    collection do
      post 'order'
    end
    member do
      get 'edit_images'
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
end

app/models/frequently_asked_question.rb
class FrequentlyAskedQuestion < ActiveRecord::Base
  validates :question, :answer, presence: true

  scope :positioned, -> { order(:position) }
  scope :displayed, -> { where(display: true).positioned }
end

app/controllers/frequently_asked_questions_controller.rb
class FrequentlyAskedQuestionsController < ApplicationController
  def index
    @presented_frequently_asked_questions = present_collection(FrequentlyAskedQuestion.displayed)
    @presented_additional_content = present(AdditionalContent.area('Home page'))
    @presented_interests = present_collection(Interest.displayed)
  end
end

app/controllers/optimadmin/additional_contents_controller.rb
module Optimadmin
  class AdditionalContentsController < Optimadmin::ApplicationController
    before_action :set_additional_content, only: [:show, :edit, :update, :destroy]

    def index
      @additional_contents = Optimadmin::BaseCollectionPresenter.new(collection: AdditionalContent.where('title ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::AdditionalContentPresenter)
    end

    def show
    end

    def new
      @additional_content = AdditionalContent.new
    end

    def edit
    end

    def create
      @additional_content = AdditionalContent.new(additional_content_params)
      if @additional_content.save
        redirect_to additional_contents_url, notice: 'Additional content was successfully created.'
      else
        render :new
      end
    end

    def update
      if @additional_content.update(additional_content_params)
        redirect_to additional_contents_url, notice: 'Additional content was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @additional_content.destroy
      redirect_to additional_contents_url, notice: 'Additional content was successfully destroyed.'
    end

  private


    def set_additional_content
      @additional_content = AdditionalContent.find(params[:id])
    end

    def additional_content_params
      params.require(:additional_content).permit(:area, :title, :content, :display)
    end
  end
end

app/controllers/optimadmin/articles_controller.rb
module Optimadmin
  class ArticlesController < Optimadmin::ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    edit_images_for Article, [[:image, { show: ['limit', 420, 83], index: ['limit', 239, 174] }]]

    def index
      @articles = Optimadmin::BaseCollectionPresenter.new(collection: Article.latest_first.where('title ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ArticlePresenter)
    end

    def show
    end

    def new
      @article = Article.new
    end

    def edit
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to articles_url, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to articles_url, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :summary, :content, :image, :remove_image, :remote_image_url, :image_cache, :date, :display, :suggested_url)
    end
  end
end

app/controllers/optimadmin/contact_query_types_controller.rb
module Optimadmin
  class ContactQueryTypesController < Optimadmin::ApplicationController
    before_action :set_contact_query_type, only: [:show, :edit, :update, :destroy]

    def index
      @contact_query_types = Optimadmin::BaseCollectionPresenter.new(collection: ContactQueryType.positioned.where('query_type ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ContactQueryTypePresenter)
    end

    def show
    end

    def new
      @contact_query_type = ContactQueryType.new
    end

    def edit
    end

    def create
      @contact_query_type = ContactQueryType.new(contact_query_type_params)
      if @contact_query_type.save
        redirect_to contact_query_types_url, notice: 'Contact query type was successfully created.'
      else
        render :new
      end
    end

    def update
      if @contact_query_type.update(contact_query_type_params)
        redirect_to contact_query_types_url, notice: 'Contact query type was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @contact_query_type.destroy
      redirect_to contact_query_types_url, notice: 'Contact query type was successfully destroyed.'
    end

  private


    def set_contact_query_type
      @contact_query_type = ContactQueryType.find(params[:id])
    end

    def contact_query_type_params
      params.require(:contact_query_type).permit(:position, :query_type, :display)
    end
  end
end

app/controllers/optimadmin/frequently_asked_questions_controller.rb
module Optimadmin
  class FrequentlyAskedQuestionsController < Optimadmin::ApplicationController
    before_action :set_frequently_asked_question, only: [:show, :edit, :update, :destroy]

    def index
      @frequently_asked_questions = Optimadmin::BaseCollectionPresenter.new(collection: FrequentlyAskedQuestion.positioned.where('question ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::FrequentlyAskedQuestionPresenter)
    end

    def show
    end

    def new
      @frequently_asked_question = FrequentlyAskedQuestion.new
    end

    def edit
    end

    def create
      @frequently_asked_question = FrequentlyAskedQuestion.new(frequently_asked_question_params)
      if @frequently_asked_question.save
        redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully created.'
      else
        render :new
      end
    end

    def update
      if @frequently_asked_question.update(frequently_asked_question_params)
        redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @frequently_asked_question.destroy
      redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully destroyed.'
    end

  private


    def set_frequently_asked_question
      @frequently_asked_question = FrequentlyAskedQuestion.find(params[:id])
    end

    def frequently_asked_question_params
      params.require(:frequently_asked_question).permit(:position, :question, :answer, :display)
    end
  end
end

app/controllers/optimadmin/home_page_banners_controller.rb
module Optimadmin
  class HomePageBannersController < Optimadmin::ApplicationController
    before_action :set_home_page_banner, only: [:show, :edit, :update, :destroy]

    edit_images_for HomePageBanner, [[:image, { show: ['fill', 545, 258] }]]

    def index
      @home_page_banners = Optimadmin::BaseCollectionPresenter.new(collection: HomePageBanner.positioned.where('title ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::HomePageBannerPresenter)
    end

    def show
    end

    def new
      @home_page_banner = HomePageBanner.new
    end

    def edit
    end

    def create
      @home_page_banner = HomePageBanner.new(home_page_banner_params)
      if @home_page_banner.save
        redirect_to home_page_banners_url, notice: 'Home page banner was successfully created.'
      else
        render :new
      end
    end

    def update
      if @home_page_banner.update(home_page_banner_params)
        redirect_to home_page_banners_url, notice: 'Home page banner was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @home_page_banner.destroy
      redirect_to home_page_banners_url, notice: 'Home page banner was successfully destroyed.'
    end

  private


    def set_home_page_banner
      @home_page_banner = HomePageBanner.find(params[:id])
    end

    def home_page_banner_params
      params.require(:home_page_banner).permit(:position, :title, :image, :remove_image, :image_cache, :remote_image_url, :content, :display)
    end
  end
end

app/controllers/optimadmin/interests_controller.rb
module Optimadmin
  class InterestsController < Optimadmin::ApplicationController
    before_action :set_interest, only: [:show, :edit, :update, :destroy]

    edit_images_for Interest, [[:image, { show: ['fill', 136, 121] }]]

    def index
      @interests = Optimadmin::BaseCollectionPresenter.new(collection: Interest.positioned.where('title ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::InterestPresenter)
    end

    def show
    end

    def new
      @interest = Interest.new
    end

    def edit
    end

    def create
      @interest = Interest.new(interest_params)
      if @interest.save
        redirect_to interests_url, notice: 'Interest was successfully created.'
      else
        render :new
      end
    end

    def update
      if @interest.update(interest_params)
        redirect_to interests_url, notice: 'Interest was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @interest.destroy
      redirect_to interests_url, notice: 'Interest was successfully destroyed.'
    end

  private


    def set_interest
      @interest = Interest.find(params[:id])
    end

    def interest_params
      params.require(:interest).permit(:position, :title, :link, :file,
      :remove_file, :file_cache, :remote_file_url, :image, :remove_image,
      :remote_image_url, :image_cache, :colour, :display)
    end
  end
end

app/controllers/optimadmin/pages_controller.rb
module Optimadmin
  class PagesController < Optimadmin::ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]

    edit_images_for Page, [[:image, { show: ['fit', 420, 83] }]]

    def index
      @pages = Optimadmin::BaseCollectionPresenter.new(collection: Page.where('title ILIKE ?', "#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::PagePresenter)
    end

    def show
    end

    def new
      @page = Page.new
    end

    def edit
    end

    def create
      @page = Page.new(page_params)
      if @page.save
        redirect_to pages_url, notice: 'Page was successfully created.'
      else
        render :new
      end
    end

    def update
      if @page.update(page_params)
        redirect_to pages_url, notice: 'Page was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @page.destroy
      redirect_to pages_url, notice: 'Page was successfully destroyed.'
    end

  private


    def set_page
      @page = Page.friendly.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :suggested_url, :image, :image_cache, :remove_image, :remote_image_url, :display, :content, :style, :layout, :sidebar)
    end
  end
end

app/helpers/frequently_asked_questions_helper.rb
module FrequentlyAskedQuestionsHelper
end

app/views/optimadmin/frequently_asked_questions/_form.html.erb
<%= form_for(@frequently_asked_question) do |f| %>
<% if @frequently_asked_question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@frequently_asked_question.errors.count, "error") %> prohibited this frequently_asked_question from being saved:</h2>

    <ul>
      <% @frequently_asked_question.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



  <div class="tabs prevent-flash">
    <ul class="tab-list">
      <li><a href="#tabs-1">Content</a></li>
      <li><a href="#tabs-3">Settings</a></li>
      <li>
        <%= link_to '#', class: 'destroy-tabs right', data: { class: 'tabs' } do %>
          <%= octicon('chevron-down') %>
        <% end %>
      </li>
    </ul>

    <%= field_set_tag nil, id: 'tabs-1' do %>

            <div class="field">
        <%= f.label :question %><br>
        <%= f.text_area :question %>
      </div>
            <div class="field">
        <%= f.label :answer %><br>
        <%= f.text_area :answer, class: 'tinymce' %>
      </div>


          <% end %>

    <%= field_set_tag nil, id: 'tabs-3' do %>
            <div class="field">
        <%= f.label :display %><br>
        <%= f.check_box :display %>
      </div>
          <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/optimadmin/frequently_asked_questions/_frequently_asked_question.html.erb
<div class="row collapse module-list-index <%= cycle('odd', 'even') %>" data-equalizer="module-list" id="item_<%= frequently_asked_question_presenter.id %>">

    <div class="large-1 hide-for-medium-down columns" data-equalizer-watch="module-list">
      <span class="drag-helper"></span>
    </div>



    <div class="large-7 small-8 columns" data-equalizer-watch="module-list">

    <%= frequently_asked_question_presenter.toggle_title %>
  </div>



  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= frequently_asked_question_presenter.toggle_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= frequently_asked_question_presenter.view_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= frequently_asked_question_presenter.edit_link %>
  </div>

  <div class="large-1 hide-for-medium-down columns last" data-equalizer-watch="module-list">
    <%= frequently_asked_question_presenter.delete_link %>
  </div>

  <div class="row module-list-detail hide" id="index-list-<%= frequently_asked_question_presenter.id %>">
    <div class="small-12 columns module-list-summary last">
      <%= frequently_asked_question_presenter.optimadmin_summary %>
    </div>
  </div>
</div>

app/views/optimadmin/frequently_asked_questions/edit.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Edit Frequently Asked Question' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: frequently_asked_questions_path, title: 'Frequently Asked Question' %>

  <%= render 'form' %>
</div>

app/views/optimadmin/frequently_asked_questions/index.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Manage Frequently Asked Questions' %>

<div class="main-content">
  <div class="row module-header collapse">
    <%= render 'optimadmin/shared/module/index/new_item', title: 'Frequently Asked Question', object: FrequentlyAskedQuestion, path: new_frequently_asked_question_path %>
    <%= render 'optimadmin/shared/search_form' %>
    <%= render 'optimadmin/shared/module/index/pagination' %>
    <!--
      <%= render 'optimadmin/shared/module/index/order', options: [['Username', 'username']] %>
    -->
    <%= render 'optimadmin/shared/module/index/recycle_bin', items: @frequently_asked_questions.size, path: root_url %>
  </div>

  <div class="row collapse module-list-index header">

      <%= list_item 'large-1 hide-for-medium-down' do %>
        <%= link_to octicon('settings') %>
      <% end %>



      <% # ADD TWO TO THE TITLE LARGE COLUMN SIZE BELOW TO ACCOUNT FOR NO IMAGE %>



      <%= list_item 'large-7 small-8' do %>
        <%= link_to octicon('chevron-down'), '#', class: 'helper-link index-list-expand-all', data: { this_class: 'octicon-chevron-up octicon-chevron-down' } %>
        Question
      <% end %>




    <%= list_item { 'Display' } %>
    <%= list_item { 'View' } %>
    <%= list_item { 'Edit' } %>

    <%= list_item('large-1 hide-for-medium-down text-center last'){ 'Delete' } %>
  </div>

  <div class='module-sortable' data-module="FrequentlyAskedQuestion">
  <%= render partial: 'frequently_asked_question', collection: @frequently_asked_questions, as: :frequently_asked_question_presenter %>
  </div>
  <%= paginate @frequently_asked_questions %>
</div>

app/views/optimadmin/frequently_asked_questions/new.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'New Frequently Asked Question' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: frequently_asked_questions_path, title: 'Frequently Asked Question' %>

  <%= render 'form' %>
</div>