config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: :show
  resources :articles, only: [:index, :show]
  resources :contacts, only: [:new, :create]

  get :frequently_asked_questions, to: 'frequently_asked_questions#index', path: 'frequently-asked-questions'

  %w( 403 404 422 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  mount Optimadmin::Engine => "/admin"
  root to: 'application#index'

  match "*path", to: "errors#show", via: :all, code: 404 unless Rails.application.config.consider_all_requests_local

end
Optimadmin::Engine.routes.draw do
  resources :contact_query_types, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  get 'article/index'

  get 'article/show'

  resources :articles, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  get 'frequently_asked_questions/index'

  resources :frequently_asked_questions, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :interests, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :additional_contents, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :home_page_banners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :home_page_banners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end

  resources :pages, except: :show do
    collection do
      post 'order'
    end
    member do
      get 'edit_images'
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
end

app/views/optimadmin/shared/sidebar/_module_links.html.erb
<div class="content-categories-sidebar">
  <div class="row collapse">
    <div class="small-8 show-for-medium-down columns">
      <%= link_to octicon('book') + 'Manage Content',
          '#',
          class: 'content-categories-toggle toggle-class',
          data: {
            class: 'content-categories-toggle-visiblity',
            container: '.content-categories, .content-categories-toggle',
            return: 'true'
          } %>
    </div>
    <div class="small-4 show-for-medium-down columns">
      <%= link_to logout_path, class: 'logout-link' do %>
        <%= octicon('sign-in') %> Logout
      <% end %>
    </div>
  </div>

  <div class="row collapse">
    <div class="large-12 small-8 left content-categories columns">
      <div class="content-category-type">
        Manage Your Content
      </div>

      <ul id="modules" class="content-category-list">
        <%= module_link(content: "Articles", model: Article, path: articles_path) %>
        <%= module_link(model: Page, path: pages_path) %>
        <%= module_link(content: "Frequently Asked Questions", model: FrequentlyAskedQuestion, path: frequently_asked_questions_path) %>
        <%= module_link(content: "Interests", model: Interest, path: interests_path) %>
        <%= module_link(content: "Additional Contents", model: AdditionalContent, path: additional_contents_path) %>
        <%= module_link(content: "Home Page Banners", model: HomePageBanner, path: home_page_banners_path) %>
        <%= module_link(content: "Contact Query Type", model: ContactQueryType, path: contact_query_types_path) %>
        <% if can? :manage, Optimadmin::MenuItem %>
          <li><%= link_to 'Site Navigation', menu_items_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>